[package]
name = "ray_trace"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.33.5", features = ["bytemuck"] }
pollster = "1.0.1"
wgpu = { version = "30.0.0", features = ["spirv"] }
winit = "0.30.13"
bytemuck = "1.25.2"
serde = { version = "1.0.229", features = ["derive"] }

[package.metadata.bundle]
name = "Wgpu Intro"
identifier = "com.twidilers.wgpu"
